### PR TITLE
Add .NET version to the footer and link to MudBlazor repo

### PR DESCRIPTION
**Pull request by danielchalmers**
## Before

image

## After

image

https://github.com/MudBlazor/TryMudBlazor/assets/7112040/b3602e92-55a7-4dc1-9a99-3ab1eefb1f4a

image

Includes automatically increasing version numbers.

### CODE REVIEW

**Comment by danielchalmers** [comment]
On the MudBlazor side: https://github.com/MudBlazor/MudBlazor/issues/8430

Needs git deep cloning in the pipeline

**Comment by mikes-gh** [comment]
Not planned ATM

**Comment by danielchalmers** [comment]
Sure np

**Comment by danielchalmers** [comment]
@mikes-gh I could remove the commit data and leave the links to .NET and MudBlazor if you want

**Comment by mikes-gh** [comment]
Thanks @danielchalmers

**Pull request merged**
