### PR TITLE
Remove explicit libraries

### PR DESCRIPTION
**Pull request by ScarletKuro**
This is a trick I found in [DotNetInternals](https://github.com/jjonescz/DotNetInternals), specifically in the following file:  
[https://github.com/jjonescz/DotNetInternals/blob/main/src/RazorAccess/RazorAccess.csproj](https://github.com/jjonescz/DotNetInternals/blob/main/src/RazorAccess/RazorAccess.csproj)

This parts:
https://github.com/MudBlazor/TryMudBlazor/blob/3e0d59c6137f6969342ebd767e195bbf56359ef1/src/Try.Core/Try.Core.csproj#L4-L5
Seems to be a workaround to gain access to `internal` classes of razor compiler.

It looks like this tool MSFT uses for testing purposes: https://lab.razor.fyi/.

To stay up-to-date with the correct assembly versions for the following packages:
- `Microsoft.CodeAnalysis.CSharp`
- `Microsoft.CodeAnalysis.CSharp.Features`
- `Microsoft.DotNet.Arcade.Sdk`
- `Microsoft.Net.Compilers.Razor.Toolset`

It’s recommended to periodically check the versions in [Directory.Packages.props](https://github.com/jjonescz/DotNetInternals/blob/main/Directory.Packages.props) from the `DotNetInternals`

While this approach may seem like a dirty workaround, it’s better than manually dragging and updating the `lib` folder ourselves. I couldn’t find an easier way to handle this, as the following packages do not seem to be included:
- `Microsoft.AspNetCore.Mvc.Razor.Extensions`
- `Microsoft.AspNetCore.Razor.Language`
- `Microsoft.AspNetCore.Razor.Utilities.Shared`
- `Microsoft.CodeAnalysis.Razor`
- `Microsoft.Extensions.ObjectPool`

Even in these nuget feeds:
https://github.com/MudBlazor/TryMudBlazor/blob/3e0d59c6137f6969342ebd767e195bbf56359ef1/src/nuget.config#L6-L9

So, I believe the magic comes from the `Microsoft.DotNet.Arcade.Sdk` reference.

### CODE REVIEW

**Comment by ScarletKuro** [comment]
I made sure that `@bind:get`, `@bind:set`, `@bind:after` from https://github.com/MudBlazor/TryMudBlazor/pull/155#issue-2626388445 are working.
The difference is also that with this the `RazorLanguageVersion` has a `RazorLanguageVersion.Version_9_0` razor version, while the public nuget only has `RazorLanguageVersion.Version_6_0`. And for `bind:set` a minimum version 7.0 support is required.

**Review by henon — APPROVED** [review]
Very interesting magic.

**Comment by mikes-gh** [comment]
Tested using

delete all bin obj directories
delete lib directory
clean
rebuild
run
test using
```
<input type="text"
    @bind:get="text"
    @bind:set="SetValue" />
    
@code {
    private string text = string.Empty;

    private void SetValue(string value)
    {
        text = value + "test";
    }
}
```
All works fine

I think you need to delete the libs directory from the repo?

**Review by mikes-gh — APPROVED** [review]

**Comment by mikes-gh** [comment]
Thanks @ScarletKuro

**Pull request merged**
